src/Entity/Info.php
<?php

namespace App\Entity;

use App\Repository\InfoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InfoRepository::class)]
class Info
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_info;

    #[ORM\Column(type: 'string', length: 255)]
    private $code_info;

    #[ORM\Column(type: 'text')]
    private $qr_info;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomInfo(): ?string
    {
        return $this->nom_info;
    }

    public function setNomInfo(string $nom_info): self
    {
        $this->nom_info = $nom_info;

        return $this;
    }

    public function getCodeInfo(): ?string
    {
        return $this->code_info;
    }

    public function setCodeInfo(string $code_info): self
    {
        $this->code_info = $code_info;

        return $this;
    }

    public function getQrInfo(): ?string
    {
        return $this->qr_info;
    }

    public function setQrInfo(string $qr_info): self
    {
        $this->qr_info = $qr_info;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/InfoType.php
<?php

namespace App\Form;

use App\Entity\Info;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InfoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_info')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Info::class,
        ]);
    }
}

src/Form/SearchType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name',TextType::class, [
                'label'=>false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Form\SearchType;
use App\Service\QrCodeService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController
{
    #[Route('/', name: 'app_default')]
    public function index(Request $request, QrCodeService $qr_code): Response
    {
        $qrCode=null;
        $form=$this->createForm(type:SearchType::class, data:null);
        $form->handleRequest($request);        
        if ($form->isSubmitted() && $form->isValid()) { 
            $data=$form->getData();
            $qrCode=$qr_code->qrcode($data['name']);
        }
        return $this->render('default/index.html.twig', [
            'form' => $form->createView(),
            'qrCode'=>$qrCode
        ]);
    }
}

src/Controller/InfoController.php
<?php

namespace App\Controller;

use App\Entity\Info;
use App\Form\InfoType;
use App\Repository\InfoRepository;
use App\Service\QrCodeService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/info')]
class InfoController extends AbstractController
{
    #[Route('/', name: 'app_info_index', methods: ['GET'])]
    public function index(InfoRepository $infoRepository): Response
    {
        return $this->render('info/index.html.twig', [
            'infos' => $infoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_info_new', methods: ['GET', 'POST'])]
    public function new(Request $request, InfoRepository $infoRepository, QrCodeService $qrcode): Response
    {
        $info = new Info();
        $form = $this->createForm(InfoType::class, $info);
        $form->handleRequest($request);
        $qr_code=null;
        if ($form->isSubmitted() && $form->isValid()) {            
            $info->setCreatedAt(new \DateTimeImmutable());
            $codeinfo= substr(uniqid($info->getNomInfo()),0,8);
            $info->setCodeInfo($codeinfo);
            $info->setQrInfo((string)$qr_code);
            $infoRepository->add($info, true);
            $qr_code=$qrcode->qrcode($info->getId(), $info->getCodeInfo());
            $info->setQrInfo((string)$qr_code);
            $infoRepository->add($info, true);
            return $this->redirectToRoute('app_info_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('info/new.html.twig', [
            'info' => $info,
            'form' => $form,
            'qrCode'=>$qr_code
        ]);
    }

    #[Route('/{id}', name: 'app_info_show', methods: ['GET'])]
    public function show(Info $info): Response
    {
        return $this->render('info/show.html.twig', [
            'info' => $info,
        ]);
    }

    #[Route('/{id}/showcode', name: 'app_info_showcode', methods: ['GET'])]
    public function showcode(Info $info): Response
    {
        return $this->render('info/showcode.html.twig', [
            'info' => $info,
        ]);
    }
    #[Route('/{id}/edit', name: 'app_info_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Info $info, InfoRepository $infoRepository): Response
    {
        $form = $this->createForm(InfoType::class, $info);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $infoRepository->add($info, true);

            return $this->redirectToRoute('app_info_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('info/edit.html.twig', [
            'info' => $info,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_info_delete', methods: ['POST'])]
    public function delete(Request $request, Info $info, InfoRepository $infoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$info->getId(), $request->request->get('_token'))) {
            $infoRepository->remove($info, true);
        }

        return $this->redirectToRoute('app_info_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
                <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% endblock %}

    </head>
    <body>
        {% block body %}{% endblock %}
        
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
              <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

<div class="example-wrapper">

    <div class="row">
        <div class="col-md-4 mx-auto">
            <div class="p-5">
                <h1>Symfony QR Code ✅</h1>
                <h2>Aller à la page info <a href="{{ path('app_info_index') }}">Cliquez ici</a></h2>
                {{ form_start(form)}}
                    {{form_row(form.name, { 'attr': {'class': 'form-control', 'placeholder': 'Recherche'}})}}
                    <hr>
                    <button type="submit" class="btn btn-success btn -block">Rechercher</button>
                {{ form_end(form)}}
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-6 mx-auto">
                {% if qrCode %}
                    <img src="{{qrCode}}" alt="qrcode" />
                {% endif %}                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/info/_delete_form.html.twig
<form method="post" action="{{ path('app_info_delete', {'id': info.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ info.id) }}">
    <button class="btn">Delete</button>
</form>

templates/info/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/info/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Info{% endblock %}

{% block body %}
    <h1>Edit Info</h1>

    {{ include('info/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_info_index') }}">back to list</a>

    {{ include('info/_delete_form.html.twig') }}
{% endblock %}

templates/info/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Info index{% endblock %}

{% block body %}
    <h1>Info index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_info</th>
                <th>Code_info</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for info in infos %}
            <tr>
                <td>{{ info.id }}</td>
                <td>{{ info.nomInfo }}</td>
                <td>{{ info.codeInfo }}</td>
                <td>{{ info.createdAt ? info.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_info_showcode', {'id': info.id}) }}">QRCode</a>
                    <a href="{{ path('app_info_edit', {'id': info.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_info_new') }}">Create new</a>
{% endblock %}

templates/info/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Info{% endblock %}

{% block body %}
    <h1>Create new Info</h1>

    {{ include('info/_form.html.twig') }}

    <a href="{{ path('app_info_index') }}">back to list</a>
    {% if qrCode %}
        <img src="{{ qrCode }}" alt="qrCode">
    {% endif %}
    
    
{% endblock %}

templates/info/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Info{% endblock %}

{% block body %}
    <h1>Info</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ info.id }}</td>
            </tr>
            <tr>
                <th>Nom_info</th>
                <td>{{ info.nomInfo }}</td>
            </tr>
            <tr>
                <th>Code_info</th>
                <td>{{ info.codeInfo }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ info.createdAt ? info.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_info_index') }}">back to list</a>

    <a href="{{ path('app_info_edit', {'id': info.id}) }}">edit</a>

    {{ include('info/_delete_form.html.twig') }}
{% endblock %}

templates/info/showcode.html.twig
{% extends 'base.html.twig' %}

{% block title %}Info index{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>Scannez le code pour avoir les informations détaillées</h1>
            <img src="{{ info.qrInfo }}" alt="{{ info.qrInfo }}" width="250">
        </div>
    </div>

{% endblock %}